application: blog-site
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /public/css
  static_dir: public/css

- url: /.*
  script: python.app.app

libraries:
- name: jinja2
  version: latest
